data = {
    'datasources': [
        {'kismet.datasource.name': 'wlan5', 'kismet.datasource.remote': 0, 'kismet.datasource.hop_offset': 0,
         'kismet.datasource.info.amp_type': '', 'kismet.datasource.dlt': 127, 'kismet.datasource.interface': 'wlan5',
         'kismet.datasource.type_driver': {'kismet.datasource.driver.probe_ipc': 1,
                                           'kismet.datasource.driver.local_capable': 1,
                                           'kismet.datasource.driver.type': 'linuxwifi',
                                           'kismet.datasource.driver.tuning_capable': 1,
                                           'kismet.datasource.driver.probe_capable': 0,
                                           'kismet.datasource.driver.description': 'Capture from Linux Wi-Fi devices using (old) wireless extensions or (new) mac80211 controls',
                                           'kismet.datasource.driver.passive_capable': 0,
                                           'kismet.datasource.driver.list_capable': 0,
                                           'kismet.datasource.driver.local_ipc': 0,
                                           'kismet.datasource.driver.list_ipc': 1,
                                           'kismet.datasource.driver.remote_capable': 1},
         'kismet.datasource.info.antenna_orientation': 0.0, 'kismet.datasource.channel': '',
         'kismet.datasource.ipc_pid': 19230, 'kismet.datasource.definition': 'wlan5:type=linuxwifi',
         'kismet.datasource.hop_channels': ['1', '1HT40+', '2', '3', '4', '5', '6', '6HT40-', '6HT40+', '7', '8', '9',
                                            '10', '11', '11HT40-', '12', '13', '14', '36', '36HT40+', '38', '40',
                                            '40HT40-', '42', '44', '44HT40+', '46', '48', '48HT40-', '52', '52HT40+',
                                            '54', '56', '56HT40-', '58', '60', '60HT40+', '62', '64', '64HT40-', '100',
                                            '100HT40+', '102', '104', '104HT40-', '106', '108', '108HT40+', '110',
                                            '112', '112HT40-', '114', '116', '116HT40+', '118', '120', '120HT40-',
                                            '122', '124', '124HT40+', '126', '128', '128HT40-', '130', '132',
                                            '132HT40+', '134', '136', '136HT40-', '138', '140', '140HT40-', '149',
                                            '149HT40+', '151', '153', '153HT40-', '155', '157', '157HT40+', '159',
                                            '161', '161HT40-', '165', '165HT40-'],
         'kismet.datasource.num_error_packets': 0, 'kismet.datasource.paused': 0,
         'kismet.datasource.channels': ['1', '1HT40+', '2', '3', '4', '5', '6', '6HT40-', '6HT40+', '7', '8', '9', '10',
                                        '11', '11HT40-', '12', '13', '14', '36', '36HT40+', '38', '40', '40HT40-', '42',
                                        '44', '44HT40+', '46', '48', '48HT40-', '52', '52HT40+', '54', '56', '56HT40-',
                                        '58', '60', '60HT40+', '62', '64', '64HT40-', '100', '100HT40+', '102', '104',
                                        '104HT40-', '106', '108', '108HT40+', '110', '112', '112HT40-', '114', '116',
                                        '116HT40+', '118', '120', '120HT40-', '122', '124', '124HT40+', '126', '128',
                                        '128HT40-', '130', '132', '132HT40+', '134', '136', '136HT40-', '138', '140',
                                        '140HT40-', '149', '149HT40+', '151', '153', '153HT40-', '155', '157',
                                        '157HT40+', '159', '161', '161HT40-', '165', '165HT40-'],
         'kismet.datasource.info.antenna_type': '', 'kismet.datasource.retry': 1, 'kismet.datasource.hop_rate': 5.0,
         'kismet.datasource.error_reason': '', 'kismet.datasource.info.antenna_gain': 0.0,
         'kismet.datasource.passive': 0,
         'kismet.datasource.packets_rrd': {'kismet.common.rrd.blank_val': 0, 'kismet.common.rrd.last_time': 1531153600,
                                           'kismet.common.rrd.minute_vec': [0, 0, 0, 21, 0, 0, 0, 0, 6, 0, 0, 2, 7, 2,
                                                                            0, 0, 4, 0, 0, 0, 0, 12, 0, 0, 0, 2, 7, 0,
                                                                            0, 0, 11, 2, 0, 0, 0, 1, 3, 0, 0, 0, 9, 0,
                                                                            0, 3, 3, 0, 0, 0, 3, 2, 0, 0, 0, 7, 1, 0, 0,
                                                                            0, 3, 0],
                                           'kismet.common.rrd.aggregator': 'default'},
         'kismet.datasource.warning': "System-wide wireless regulatory domain is set to '00'; this can cause problems setting channels.  If you encounter problems, set the regdom with a command like 'sudo iw reg set US' or whatever country is appropriate for your location.",
         'kismet.datasource.running': 1, 'kismet.datasource.info.amp_gain': 0.0,
         'kismet.datasource.ipc_binary': 'kismet_cap_linux_wifi', 'kismet.datasource.info.antenna_beamwidth': 0.0,
         'kismet.datasource.hop_shuffle': 1, 'kismet.datasource.hop_shuffle_skip': 4,
         'kismet.datasource.hardware': 'rt2800usb', 'kismet.datasource.hopping': 1,
         'kismet.datasource.capture_interface': 'wlan5mon', 'kismet.datasource.num_packets': 984,
         'kismet.datasource.hop_split': 0, 'kismet.datasource.source_number': 1,
         'kismet.datasource.uuid': '5fe308bd-0000-0000-0000-24050f73b68f', 'kismet.datasource.source_key': 2607351894,
         'kismet.datasource.error': 0, 'kismet.datasource.retry_attempts': 0,
         'kismet.datasource.total_retry_attempts': 0}],
    'messages': [{'kismet.messagebus.message_time': 1531153116,
                  'kismet.messagebus.message_string': 'Detected new 802.11 Wi-Fi access point E8:DF:70:12:23:34 packet 19',
                  'kismet.messagebus.message_flags': 2}, {'kismet.messagebus.message_time': 1531153116,
                                                          'kismet.messagebus.message_string': "802.11 Wi-Fi device E8:DF:70:12:23:34 advertising SSID 'asdfgh'",
                                                          'kismet.messagebus.message_flags': 2},
                 {'kismet.messagebus.message_time': 1531153116,
                  'kismet.messagebus.message_string': 'Detected new 802.11 Wi-Fi access point B0:98:2B:23:34:35 packet 21',
                  'kismet.messagebus.message_flags': 2}, {'kismet.messagebus.message_time': 1531153116,
                                                          'kismet.messagebus.message_string': "802.11 Wi-Fi device B0:98:2B:23:34:35 advertising SSID 'yxcvbn,'",
                                                          'kismet.messagebus.message_flags': 2},
                 {'kismet.messagebus.message_time': 1531153576,
                  'kismet.messagebus.message_string': "802.11 Wi-Fi device E8:DF:70:23:44:52 advertising SSID 'qwertzu'",
                  'kismet.messagebus.message_flags': 2}, {'kismet.messagebus.message_time': 1531153576,
                                                          'kismet.messagebus.message_string': 'Detected new 802.11 Wi-Fi device E8:DF:70:23:44:52 packet 937',
                                                          'kismet.messagebus.message_flags': 2}],
    'dot11': [
        {'kismet.device.base.last_time': 1531153589, 'kismet.device.base.key': '4202770D33078F47_E6612C6D28E00000',
         'kismet.common.signal.peak_loc': {'kismet.common.location.speed': 0.0, 'kismet.common.location.alt': 39.299999,
                                           'kismet.common.location.time_sec': 1531153119,
                                           'kismet.common.location.lon': 13.543111,
                                           'kismet.common.location.lat': 52.235019,
                                           'kismet.common.location.heading': 0.0,
                                           'kismet.common.location.time_usec': 596336,
                                           'kismet.common.location.valid': 1, 'kismet.common.location.fix': 3},
         'dot11.device': {'dot11.device.last_probed_ssid_csum': 0, 'dot11.device.wpa_handshake_list': [],
                          'dot11.device.datasize': 0, 'dot11.device.last_beaconed_ssid_checksum': 139002381,
                          'dot11.device.wps_m3_last': 0, 'dot11.device.last_sequence': 0, 'dot11.device.typeset': 1,
                          'dot11.device.last_bssid': '00:00:00:00:00:00', 'dot11.device.client_map': {},
                          'dot11.device.num_retries': 0, 'dot11.device.last_probed_ssid': '',
                          'dot11.device.num_probed_ssids': 0, 'dot11.device.probed_ssid_map': {},
                          'dot11.device.advertised_ssid_map': [ {'dot11.advertisedssid.beacon_info': '',
                                                                             'dot11.advertisedssid.ht_center_2': 0,
                                                                             'dot11.advertisedssid.ssid': 'asdfgfh',
                                                                             'dot11.advertisedssid.wps_device_name': '',
                                                                             'dot11.advertisedssid.last_time': 1531153589,
                                                                             'dot11.advertisedssid.location': {
                                                                                 'kismet.common.location.min_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.299999,
                                                                                     'kismet.common.location.time_sec': 0,
                                                                                     'kismet.common.location.geopoint': [13.543111, 52.235019],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 0,
                                                                                     'kismet.common.location.valid': 0,
                                                                                     'kismet.common.location.fix': 0},
                                                                                 'kismet.common.location.avg_alt': 785998,
                                                                                 'kismet.common.location.max_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.299999,
                                                                                     'kismet.common.location.time_sec': 0,
                                                                                     'kismet.common.location.geopoint': [13.543111, 52.235019],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 0,
                                                                                     'kismet.common.location.valid': 0,
                                                                                     'kismet.common.location.fix': 0},
                                                                                 'kismet.common.location.loc_fix': 3,
                                                                                 'kismet.common.location.avg_lat': 1580220,
                                                                                 'kismet.common.location.loc_valid': 1,
                                                                                 'kismet.common.location.avg_lon': 397833,
                                                                                 'kismet.common.location.avg_num': 3,
                                                                                 'kismet.common.location.avg_alt_num': 2,
                                                                                 'kismet.common.location.avg_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.2999,
                                                                                     'kismet.common.location.time_sec': 1531153310,
                                                                                     'kismet.common.location.geopoint': [13.543111, 52.235019],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 998569,
                                                                                     'kismet.common.location.valid': 1,
                                                                                     'kismet.common.location.fix': 3}},
                                                                             'dot11.advertisedssid.beaconrate': 10,
                                                                             'dot11.advertisedssid.dot11e_qbss_stations': 0,
                                                                             'dot11.advertisedssid.ietag_checksum': 2555649638,
                                                                             'dot11.advertisedssid.ht_mode': 'HT20',
                                                                             'dot11.advertisedssid.cloaked': 0,
                                                                             'dot11.advertisedssid.channel': '1',
                                                                             'dot11.advertisedssid.beacons_sec': 63,
                                                                             'dot11.advertisedssid.probe_response': 1,
                                                                             'dot11.advertisedssid.maxrate': 866,
                                                                             'dot11.advertisedssid.wps_model_name': 'FBox',
                                                                             'dot11.advertisedssid.dot11r_mobility_domain_id': 0,
                                                                             'dot11.advertisedssid.dot11e_channel_utilization_perc': 0.0,
                                                                             'dot11.advertisedssid.dot11d_list': [
                                                                                 {'dot11.11d.tx_power': 20,
                                                                                  'dot11.11d.num_channels': 13,
                                                                                  'dot11.11d.start_channel': 1}],
                                                                             'dot11.advertisedssid.wps_serial_number': '0000',
                                                                             'dot11.advertisedssid.wps_model_number': '0000',
                                                                             'dot11.advertisedssid.first_time': 1531153105,
                                                                             'dot11.advertisedssid.dot11e_qbss': 0,
                                                                             'dot11.advertisedssid.dot11r_mobility': 0,
                                                                             'dot11.advertisedssid.dot11d_country': 'DE',
                                                                             'dot11.advertisedssid.wps_state': 1,
                                                                             'dot11.advertisedssid.beacon': 1,
                                                                             'dot11.advertisedssid.ssidlen': 7,
                                                                             'dot11.advertisedssid.ht_center_1': 0,
                                                                             'dot11.advertisedssid.wps_manuf': 'AVM',
                                                                             'dot11.advertisedssid.crypt_set': 268436162}],
                          'dot11.device.num_associated_clients': 0, 'dot11.device.num_client_aps': 0,
                          'dot11.device.associated_client_map': {}, 'dot11.device.client_disconnects': 0,
                          'dot11.device.wpa_anonce_list': [], 'dot11.device.last_beacon_timestamp': 1531153589,
                          'dot11.device.wpa_present_handshake': 0, 'dot11.device.bss_timestamp': 0,
                          'dot11.device.wpa_nonce_list': [], 'dot11.device.num_advertised_ssids': 1,
                          'dot11.device.wps_m3_count': 0, 'dot11.device.last_beaconed_ssid': 'K_2G_DG',
                          'dot11.device.num_fragments': 0, 'dot11.device.datasize_retry': 0, },
         'kismet.device.base.seenby': [ {'kismet.common.seenby.num_packets': 67,
                                                       'kismet.common.seenby.uuid': '5fe308bd-0000-0000-0000-24050f73b68f',
                                                       'kismet.common.seenby.first_time': 1531153105,
                                                       'kismet.common.seenby.last_time': 1531153589,
                                                       'kismet.common.seenby.signal': {
                                                           'kismet.common.signal.carrierset': 5,
                                                           'kismet.common.signal.min_noise_dbm': 0,
                                                           'kismet.common.signal.encodingset': 3,
                                                           'kismet.common.signal.max_noise_dbm': 0,
                                                           'kismet.common.signal.last_noise_rssi': 0,
                                                           'kismet.common.signal.peak_loc': {
                                                               'kismet.common.location.speed': 0.0,
                                                               'kismet.common.location.alt': 39.299999,
                                                               'kismet.common.location.time_sec': 1531153119,
                                                               'kismet.common.location.lon': 13.543111,
                                                               'kismet.common.location.lat': 52.235019,
                                                               'kismet.common.location.heading': 0.0,
                                                               'kismet.common.location.time_usec': 596418,
                                                               'kismet.common.location.valid': 1,
                                                               'kismet.common.location.fix': 3},
                                                           'kismet.common.signal.last_signal_rssi': 0,
                                                           'kismet.common.signal.last_noise_dbm': 0,
                                                           'kismet.common.signal.last_signal_dbm': -86,
                                                           'kismet.common.signal.max_signal_rssi': 0,
                                                           'kismet.common.signal.min_signal_dbm': -90,
                                                           'kismet.common.signal.signal_rrd': {
                                                               'kismet.common.rrd.blank_val': 0,
                                                               'kismet.common.rrd.last_time': 1531153600,
                                                               'kismet.common.rrd.minute_vec': [0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, -86, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, 0,
                                                                                                -86, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, -84, 0, 0, 0,
                                                                                                0, -86, 0, 0, 0, 0, 0,
                                                                                                0],
                                                               'kismet.common.rrd.aggregator': 'peak_signal'},
                                                           'kismet.common.signal.min_noise_rssi': 0,
                                                           'kismet.common.signal.max_signal_dbm': -82,
                                                           'kismet.common.signal.max_noise_rssi': 0,
                                                           'kismet.common.signal.min_signal_rssi': 0,
                                                           'kismet.common.signal.maxseenrate': 60.0},
                                                       'kismet.common.seenby.freq_khz_map': {'2412000': 67}}],
         'kismet.device.base.first_time': 1531153105, 'kismet.common.signal.last_signal': -86,
         'kismet.common.signal.min_signal': -90, 'kismet.device.base.channel': '1',
         'kismet.device.base.macaddr': '00:12:2A:03:B9:12', 'kismet.common.signal.max_signal': -82,
         'kismet.device.base.crypt': 'WPA-CCMP',
         'kismet.common.signal.type': 'dbm', 'kismet.device.base.manuf': 'AvmAudio'},
        {'kismet.device.base.last_time': 1531153589, 'kismet.device.base.key': '4202770D33078F47_E6612C6D28E20000',
         'kismet.common.signal.peak_loc': {'kismet.common.location.speed': 0.0, 'kismet.common.location.alt': 39.299999,
                                           'kismet.common.location.time_sec': 1531153119,
                                           'kismet.common.location.lon': 13.261111,
                                           'kismet.common.location.lat': 52.674019,
                                           'kismet.common.location.heading': 0.0,
                                           'kismet.common.location.time_usec': 596604,
                                           'kismet.common.location.valid': 1, 'kismet.common.location.fix': 3},
         'dot11.device': {'dot11.device.last_probed_ssid_csum': 0, 'dot11.device.wpa_handshake_list': [],
                          'dot11.device.datasize': 0, 'dot11.device.last_beaconed_ssid_checksum': 244974423,
                          'dot11.device.wps_m3_last': 0, 'dot11.device.last_sequence': 0, 'dot11.device.typeset': 1,
                          'dot11.device.last_bssid': '00:00:00:00:00:00', 'dot11.device.client_map': {},
                          'dot11.device.num_retries': 0, 'dot11.device.last_probed_ssid': '',
                          'dot11.device.num_probed_ssids': 0, 'dot11.device.probed_ssid_map': {},
                          'dot11.device.advertised_ssid_map': [ {'dot11.advertisedssid.beacon_info': '',
                                                                             'dot11.advertisedssid.ht_center_2': 0,
                                                                             'dot11.advertisedssid.ssid': 'wqsdd',
                                                                             'dot11.advertisedssid.wps_device_name': '',
                                                                             'dot11.advertisedssid.last_time': 1531153589,
                                                                             'dot11.advertisedssid.location': {
                                                                                 'kismet.common.location.min_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.299999,
                                                                                     'kismet.common.location.time_sec': 0,
                                                                                     'kismet.common.location.geopoint': [13.261111, 52.674019],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 0,
                                                                                     'kismet.common.location.valid': 0,
                                                                                     'kismet.common.location.fix': 0},
                                                                                 'kismet.common.location.avg_alt': 785998,
                                                                                 'kismet.common.location.max_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.299999,
                                                                                     'kismet.common.location.time_sec': 0,
                                                                                     'kismet.common.location.geopoint': [13.261111, 52.674019],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 0,
                                                                                     'kismet.common.location.valid': 0,
                                                                                     'kismet.common.location.fix': 0},
                                                                                 'kismet.common.location.loc_fix': 3,
                                                                                 'kismet.common.location.avg_lat': 1580220,
                                                                                 'kismet.common.location.loc_valid': 1,
                                                                                 'kismet.common.location.avg_lon': 397833,
                                                                                 'kismet.common.location.avg_num': 3,
                                                                                 'kismet.common.location.avg_alt_num': 2,
                                                                                 'kismet.common.location.avg_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.2999,
                                                                                     'kismet.common.location.time_sec': 1531153310,
                                                                                     'kismet.common.location.geopoint': [13.261111, 52.674019],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 998991,
                                                                                     'kismet.common.location.valid': 1,
                                                                                     'kismet.common.location.fix': 3}},
                                                                             'dot11.advertisedssid.beaconrate': 10,
                                                                             'dot11.advertisedssid.dot11e_qbss_stations': 0,
                                                                             'dot11.advertisedssid.ietag_checksum': 1100817844,
                                                                             'dot11.advertisedssid.ht_mode': 'HT20',
                                                                             'dot11.advertisedssid.cloaked': 0,
                                                                             'dot11.advertisedssid.channel': '1',
                                                                             'dot11.advertisedssid.beacons_sec': 54,
                                                                             'dot11.advertisedssid.probe_response': 1,
                                                                             'dot11.advertisedssid.maxrate': 866,
                                                                             'dot11.advertisedssid.wps_model_name': 'FBox',
                                                                             'dot11.advertisedssid.dot11r_mobility_domain_id': 0,
                                                                             'dot11.advertisedssid.dot11e_channel_utilization_perc': 0.0,
                                                                             'dot11.advertisedssid.dot11d_list': [
                                                                                 {'dot11.11d.tx_power': 20,
                                                                                  'dot11.11d.num_channels': 13,
                                                                                  'dot11.11d.start_channel': 1}],
                                                                             'dot11.advertisedssid.wps_serial_number': '0000',
                                                                             'dot11.advertisedssid.wps_model_number': '0000',
                                                                             'dot11.advertisedssid.first_time': 1531153105,
                                                                             'dot11.advertisedssid.dot11e_qbss': 0,
                                                                             'dot11.advertisedssid.dot11r_mobility': 0,
                                                                             'dot11.advertisedssid.dot11d_country': 'DE',
                                                                             'dot11.advertisedssid.wps_state': 1,
                                                                             'dot11.advertisedssid.beacon': 1,
                                                                             'dot11.advertisedssid.ssidlen': 8,
                                                                             'dot11.advertisedssid.ht_center_1': 0,
                                                                             'dot11.advertisedssid.wps_manuf': 'AVM',
                                                                             'dot11.advertisedssid.crypt_set': 402653922}],
                          'dot11.device.num_associated_clients': 0, 'dot11.device.num_client_aps': 0,
                          'dot11.device.associated_client_map': {}, 'dot11.device.client_disconnects': 0,
                          'dot11.device.wpa_anonce_list': [], 'dot11.device.last_beacon_timestamp': 1531153589,
                          'dot11.device.wpa_present_handshake': 0, 'dot11.device.bss_timestamp': 0,
                          'dot11.device.wpa_nonce_list': [], 'dot11.device.num_advertised_ssids': 1,
                          'dot11.device.wps_m3_count': 0, 'dot11.device.last_beaconed_ssid': 'Kunzgast',
                          'dot11.device.num_fragments': 0, 'dot11.device.datasize_retry': 0},
         'kismet.device.base.seenby': [{'kismet.common.seenby.num_packets': 58,
                                                       'kismet.common.seenby.uuid': '5fe308bd-0000-0000-0000-24050f73b68f',
                                                       'kismet.common.seenby.first_time': 1531153105,
                                                       'kismet.common.seenby.last_time': 1531153589,
                                                       'kismet.common.seenby.signal': {
                                                           'kismet.common.signal.carrierset': 5,
                                                           'kismet.common.signal.min_noise_dbm': 0,
                                                           'kismet.common.signal.encodingset': 3,
                                                           'kismet.common.signal.max_noise_dbm': 0,
                                                           'kismet.common.signal.last_noise_rssi': 0,
                                                           'kismet.common.signal.peak_loc': {
                                                               'kismet.common.location.speed': 0.0,
                                                               'kismet.common.location.alt': 39.299999,
                                                               'kismet.common.location.time_sec': 1531153119,
                                                               'kismet.common.location.lon': 13.261111,
                                                               'kismet.common.location.lat': 52.674019,
                                                               'kismet.common.location.heading': 0.0,
                                                               'kismet.common.location.time_usec': 596685,
                                                               'kismet.common.location.valid': 1,
                                                               'kismet.common.location.fix': 3},
                                                           'kismet.common.signal.last_signal_rssi': 0,
                                                           'kismet.common.signal.last_noise_dbm': 0,
                                                           'kismet.common.signal.last_signal_dbm': -90,
                                                           'kismet.common.signal.max_signal_rssi': 0,
                                                           'kismet.common.signal.min_signal_dbm': -90,
                                                           'kismet.common.signal.signal_rrd': {
                                                               'kismet.common.rrd.blank_val': 0,
                                                               'kismet.common.rrd.last_time': 1531153600,
                                                               'kismet.common.rrd.minute_vec': [0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, -84, 0, 0, 0, 0, -90,
                                                                                                0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, -86,
                                                                                                0, 0, 0, 0, 0, 0],
                                                               'kismet.common.rrd.aggregator': 'peak_signal'},
                                                           'kismet.common.signal.min_noise_rssi': 0,
                                                           'kismet.common.signal.max_signal_dbm': -82,
                                                           'kismet.common.signal.max_noise_rssi': 0,
                                                           'kismet.common.signal.min_signal_rssi': 0,
                                                           'kismet.common.signal.maxseenrate': 60.0},
                                                       'kismet.common.seenby.freq_khz_map': {'2412000': 58}}],
         'kismet.device.base.first_time': 1531153105, 'kismet.common.signal.last_signal': -90,
         'kismet.common.signal.min_signal': -90, 'kismet.device.base.channel': '1',
         'kismet.device.base.macaddr': 'E2:28:6D:22:33:44', 'kismet.common.signal.max_signal': -82,
         'kismet.device.base.crypt': 'WPA-TKIP',
         'kismet.common.signal.type': 'dbm', 'kismet.device.base.manuf': 'Unknown'},
        {'kismet.device.base.last_time': 1531153599, 'kismet.device.base.key': '4202770D33078F47_E500C684AC0000',
         'kismet.common.signal.peak_loc': {'kismet.common.location.speed': 0.0, 'kismet.common.location.alt': 39.299999,
                                           'kismet.common.location.time_sec': 1531153217,
                                           'kismet.common.location.lon': 13.123456,
                                           'kismet.common.location.lat': 52.123456,
                                           'kismet.common.location.heading': 0.0,
                                           'kismet.common.location.time_usec': 925320,
                                           'kismet.common.location.valid': 1, 'kismet.common.location.fix': 2},
         'dot11.device': {'dot11.device.last_probed_ssid_csum': 0, 'dot11.device.wpa_handshake_list': [],
                          'dot11.device.datasize': 0, 'dot11.device.last_beaconed_ssid_checksum': 101384641,
                          'dot11.device.wps_m3_last': 0, 'dot11.device.last_sequence': 0, 'dot11.device.typeset': 1,
                          'dot11.device.last_bssid': '00:00:00:00:00:00', 'dot11.device.client_map': {},
                          'dot11.device.num_retries': 0, 'dot11.device.last_probed_ssid': '',
                          'dot11.device.num_probed_ssids': 0, 'dot11.device.probed_ssid_map': {},
                          'dot11.device.advertised_ssid_map': [ {'dot11.advertisedssid.beacon_info': '',
                                                                             'dot11.advertisedssid.ht_center_2': 0,
                                                                             'dot11.advertisedssid.ssid': 'GARTEN',
                                                                             'dot11.advertisedssid.wps_device_name': '',
                                                                             'dot11.advertisedssid.last_time': 1531153599,
                                                                             'dot11.advertisedssid.location': {
                                                                                 'kismet.common.location.min_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.299999,
                                                                                     'kismet.common.location.time_sec': 0,
                                                                                     'kismet.common.location.geopoint': [13.123456, 52.123456],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 0,
                                                                                     'kismet.common.location.valid': 0,
                                                                                     'kismet.common.location.fix': 0},
                                                                                 'kismet.common.location.avg_alt': 3143992,
                                                                                 'kismet.common.location.max_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.299999,
                                                                                     'kismet.common.location.time_sec': 0,
                                                                                     'kismet.common.location.geopoint': [13.123456, 52.123456],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 0,
                                                                                     'kismet.common.location.valid': 0,
                                                                                     'kismet.common.location.fix': 0},
                                                                                 'kismet.common.location.loc_fix': 3,
                                                                                 'kismet.common.location.avg_lat': 5267400,
                                                                                 'kismet.common.location.loc_valid': 1,
                                                                                 'kismet.common.location.avg_lon': 1326110,
                                                                                 'kismet.common.location.avg_num': 10,
                                                                                 'kismet.common.location.avg_alt_num': 8,
                                                                                 'kismet.common.location.avg_loc': {
                                                                                     'kismet.common.location.speed': 0.0,
                                                                                     'kismet.common.location.alt': 39.2999,
                                                                                     'kismet.common.location.time_sec': 1531153563,
                                                                                     'kismet.common.location.geopoint': [13.123456, 52.123456],
                                                                                     'kismet.common.location.heading': 0.0,
                                                                                     'kismet.common.location.time_usec': 269632,
                                                                                     'kismet.common.location.valid': 1,
                                                                                     'kismet.common.location.fix': 3}},
                                                                             'dot11.advertisedssid.beaconrate': 10,
                                                                             'dot11.advertisedssid.dot11e_qbss_stations': 0,
                                                                             'dot11.advertisedssid.ietag_checksum': 107093117,
                                                                             'dot11.advertisedssid.ht_mode': 'HT20',
                                                                             'dot11.advertisedssid.cloaked': 0,
                                                                             'dot11.advertisedssid.channel': '6',
                                                                             'dot11.advertisedssid.beacons_sec': 147,
                                                                             'dot11.advertisedssid.probe_response': 1,
                                                                             'dot11.advertisedssid.maxrate': 866,
                                                                             'dot11.advertisedssid.wps_model_name': 'TL-WA901ND',
                                                                             'dot11.advertisedssid.dot11r_mobility_domain_id': 0,
                                                                             'dot11.advertisedssid.dot11e_channel_utilization_perc': 0.0,
                                                                             'dot11.advertisedssid.dot11d_list': [],
                                                                             'dot11.advertisedssid.wps_serial_number': '1.0',
                                                                             'dot11.advertisedssid.wps_model_number': '5.0',
                                                                             'dot11.advertisedssid.first_time': 1531153105,
                                                                             'dot11.advertisedssid.dot11e_qbss': 0,
                                                                             'dot11.advertisedssid.dot11r_mobility': 0,
                                                                             'dot11.advertisedssid.dot11d_country': '',
                                                                             'dot11.advertisedssid.wps_state': 1,
                                                                             'dot11.advertisedssid.beacon': 1,
                                                                             'dot11.advertisedssid.ssidlen': 6,
                                                                             'dot11.advertisedssid.ht_center_1': 0,
                                                                             'dot11.advertisedssid.wps_manuf': 'TP-LINK',
                                                                             'dot11.advertisedssid.crypt_set': 268436162}],
                          'dot11.device.num_associated_clients': 0, 'dot11.device.num_client_aps': 0,
                          'dot11.device.associated_client_map': {}, 'dot11.device.client_disconnects': 0,
                          'dot11.device.wpa_anonce_list': [], 'dot11.device.last_beacon_timestamp': 1531153599,
                          'dot11.device.wpa_present_handshake': 0, 'dot11.device.bss_timestamp': 0,
                          'dot11.device.wpa_nonce_list': [], 'dot11.device.num_advertised_ssids': 1,
                          'dot11.device.wps_m3_count': 0, 'dot11.device.last_beaconed_ssid': 'Test',
                          'dot11.device.num_fragments': 0, 'dot11.device.datasize_retry': 0},
         'kismet.device.base.seenby': [{'kismet.common.seenby.num_packets': 179,
                                                       'kismet.common.seenby.uuid': '5fe308bd-0000-0000-0000-24050f73b68f',
                                                       'kismet.common.seenby.first_time': 1531153105,
                                                       'kismet.common.seenby.last_time': 1531153599,
                                                       'kismet.common.seenby.signal': {
                                                           'kismet.common.signal.carrierset': 1,
                                                           'kismet.common.signal.min_noise_dbm': 0,
                                                           'kismet.common.signal.encodingset': 1,
                                                           'kismet.common.signal.max_noise_dbm': 0,
                                                           'kismet.common.signal.last_noise_rssi': 0,
                                                           'kismet.common.signal.peak_loc': {
                                                               'kismet.common.location.speed': 0.0,
                                                               'kismet.common.location.alt': 39.299999,
                                                               'kismet.common.location.time_sec': 1531153217,
                                                               'kismet.common.location.lon': 13.123456,
                                                               'kismet.common.location.lat': 52.123456,
                                                               'kismet.common.location.heading': 0.0,
                                                               'kismet.common.location.time_usec': 925321,
                                                               'kismet.common.location.valid': 1,
                                                               'kismet.common.location.fix': 2},
                                                           'kismet.common.signal.last_signal_rssi': 0,
                                                           'kismet.common.signal.last_noise_dbm': 0,
                                                           'kismet.common.signal.last_signal_dbm': -90,
                                                           'kismet.common.signal.max_signal_rssi': 0,
                                                           'kismet.common.signal.min_signal_dbm': -90,
                                                           'kismet.common.signal.signal_rrd': {
                                                               'kismet.common.rrd.blank_val': 0,
                                                               'kismet.common.rrd.last_time': 1531153600,
                                                               'kismet.common.rrd.minute_vec': [0, 0, 0, -86, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, -84, 0,
                                                                                                0, 0, -86, 0, 0, 0, 0,
                                                                                                0, 0, 0, 0, 0, 0, 0, 0,
                                                                                                0, -86, 0, 0, 0, 0, 0,
                                                                                                -84, 0, 0, 0, 0, 0, 0,
                                                                                                -88, 0, 0, 0, 0, 0, 0,
                                                                                                0, 0, 0, -86, 0, 0, 0,
                                                                                                0, -84, 0],
                                                               'kismet.common.rrd.aggregator': 'peak_signal'},
                                                           'kismet.common.signal.min_noise_rssi': 0,
                                                           'kismet.common.signal.max_signal_dbm': -82,
                                                           'kismet.common.signal.max_noise_rssi': 0,
                                                           'kismet.common.signal.min_signal_rssi': 0,
                                                           'kismet.common.signal.maxseenrate': 10.0},
                                                       'kismet.common.seenby.freq_khz_map': {'2437000': 179}}],
         'kismet.device.base.first_time': 1531153105, 'kismet.common.signal.last_signal': -90,
         'kismet.common.signal.min_signal': -90, 'kismet.device.base.channel': '6',
         'kismet.device.base.macaddr': 'AC:84:C6:11:22:33', 'kismet.common.signal.max_signal': -82,
         'kismet.device.base.crypt': 'Open',
         'kismet.common.signal.type': 'dbm', 'kismet.device.base.manuf': 'Unknown'},
    ],
    'status': {'kismet.system.battery.percentage': 0, 'kismet.system.memory.rss': 41432, 'kismet.system.battery.ac': 1,
               'kismet.system.server_uuid': 'b05187e6-77d3-11e8-aa0b-4b49534d4234', 'kismet.system.server_name': '',
               'kismet.system.server_location': '', 'kismet.system.battery.charging': 'charged',
               'kismet.system.devices.count': 44, 'kismet.system.server_description': '', 'kismet.system.user': 'root',
               'kismet.system.timestamp.sec': 1531153600, 'kismet.system.timestamp.start_sec': 1531153070,
               'kismet.system.battery.remaining': 0, 'kismet.system.timestamp.usec': 338221},
    'location': [{'kismet.common.location.speed': 0.0,
                  'kismet.common.location.alt': 39.299999,
                  'kismet.common.location.time_sec': 1531153599,
                  'kismet.common.location.geopoint': [13.123456, 52.123456],
                  'kismet.common.location.heading': 0.0,
                  'kismet.common.location.time_usec': 116800,
                  'kismet.common.location.valid': 1,
                  'kismet.common.location.fix': 2,
                  'kismet.common.location.gps_uuid': '17180436-0000-0000-0000-000080dc10aa'}],
}
available_datasources = [{'kismet.datasource.type_driver': {'kismet.datasource.driver.type': 'linuxbluetooth',
                                                           'kismet.datasource.driver.description': 'Capture from Linux Bluetooth devices using the Linux kernel drivers and Blue-Z',
                                                           'kismet.datasource.driver.probe_capable': 1,
                                                           'kismet.datasource.driver.probe_ipc': 0,
                                                           'kismet.datasource.driver.list_capable': 1,
                                                           'kismet.datasource.driver.list_ipc': 0,
                                                           'kismet.datasource.driver.local_capable': 1,
                                                           'kismet.datasource.driver.local_ipc': 0,
                                                           'kismet.datasource.driver.remote_capable': 1,
                                                           'kismet.datasource.driver.passive_capable': 0,
                                                           'kismet.datasource.driver.tuning_capable': 0},
                         'kismet.datasource.probed.interface': 'hci0', 'kismet.datasource.probed.options_vec': [],
                         'kismet.datasource.probed.in_use_uuid': '00000000-0000-0000-0000-000000000000',
                         'kismet.datasource.probed.hardware': 'linuxhci'}, {
                            'kismet.datasource.type_driver': {'kismet.datasource.driver.type': 'linuxwifi',
                                                              'kismet.datasource.driver.description': 'Capture from Linux Wi-Fi devices using (old) wireless extensions or (new) mac80211 controls',
                                                              'kismet.datasource.driver.probe_capable': 1,
                                                              'kismet.datasource.driver.probe_ipc': 0,
                                                              'kismet.datasource.driver.list_capable': 1,
                                                              'kismet.datasource.driver.list_ipc': 0,
                                                              'kismet.datasource.driver.local_capable': 1,
                                                              'kismet.datasource.driver.local_ipc': 0,
                                                              'kismet.datasource.driver.remote_capable': 1,
                                                              'kismet.datasource.driver.passive_capable': 0,
                                                              'kismet.datasource.driver.tuning_capable': 1},
                            'kismet.datasource.probed.interface': 'wlo1', 'kismet.datasource.probed.options_vec': [],
                            'kismet.datasource.probed.in_use_uuid': '00000000-0000-0000-0000-000000000000',
                            'kismet.datasource.probed.hardware': 'iwlwifi'}, {
                            'kismet.datasource.type_driver': {'kismet.datasource.driver.type': 'linuxwifi',
                                                              'kismet.datasource.driver.description': 'Capture from Linux Wi-Fi devices using (old) wireless extensions or (new) mac80211 controls',
                                                              'kismet.datasource.driver.probe_capable': 1,
                                                              'kismet.datasource.driver.probe_ipc': 0,
                                                              'kismet.datasource.driver.list_capable': 1,
                                                              'kismet.datasource.driver.list_ipc': 0,
                                                              'kismet.datasource.driver.local_capable': 1,
                                                              'kismet.datasource.driver.local_ipc': 0,
                                                              'kismet.datasource.driver.remote_capable': 1,
                                                              'kismet.datasource.driver.passive_capable': 0,
                                                              'kismet.datasource.driver.tuning_capable': 1},
                            'kismet.datasource.probed.interface': 'wlan0', 'kismet.datasource.probed.options_vec': [],
                            'kismet.datasource.probed.in_use_uuid': '00000000-0000-0000-0000-000000000001',
                            'kismet.datasource.probed.hardware': 'iwlwifi'}, {
                            'kismet.datasource.type_driver': {'kismet.datasource.driver.type': 'linuxwifi',
                                                              'kismet.datasource.driver.description': 'Capture from Linux Wi-Fi devices using (old) wireless extensions or (new) mac80211 controls',
                                                              'kismet.datasource.driver.probe_capable': 1,
                                                              'kismet.datasource.driver.probe_ipc': 0,
                                                              'kismet.datasource.driver.list_capable': 1,
                                                              'kismet.datasource.driver.list_ipc': 0,
                                                              'kismet.datasource.driver.local_capable': 1,
                                                              'kismet.datasource.driver.local_ipc': 0,
                                                              'kismet.datasource.driver.remote_capable': 1,
                                                              'kismet.datasource.driver.passive_capable': 0,
                                                              'kismet.datasource.driver.tuning_capable': 1},
                            'kismet.datasource.probed.interface': 'wlan0mon', 'kismet.datasource.probed.options_vec': [],
                            'kismet.datasource.probed.in_use_uuid': '00000000-0000-0000-0000-000000000001',
                            'kismet.datasource.probed.hardware': 'iwlwifi'}]
