.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Patrick Salecker <mail@salecker.org>,
.\"
.TH KISMON 1 "July 13, 2015"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
kismon \- kismet client gui
.SH SYNOPSIS
.B kismon
.RI [ options ]
.br
.SH DESCRIPTION
.B kismon
is GUI client for kismet (>=2019-?-?) with a live map of the networks.
.SH OPTIONS
These options are mainly thought for debugging purposes.
.TP
.B \-\-disable\-map
Disable OSM Map.
.TP
.SH SEE ALSO
.BR kismet (1)
